src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="integer")
     */
    private $access_robot;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sip_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sip_password;

    /**
     * @ORM\Column(type="integer")
     */
    private $closer_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fullname;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="integer")
     */
    private $Balance;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAccessRobot(): ?int
    {
        return $this->access_robot;
    }

    public function setAccessRobot(int $access_robot): self
    {
        $this->access_robot = $access_robot;

        return $this;
    }

    public function getSipId(): ?string
    {
        return $this->sip_id;
    }

    public function setSipId(string $sip_id): self
    {
        $this->sip_id = $sip_id;

        return $this;
    }

    public function getSipPassword(): ?string
    {
        return $this->sip_password;
    }

    public function setSipPassword(string $sip_password): self
    {
        $this->sip_password = $sip_password;

        return $this;
    }

    public function getCloserId(): ?int
    {
        return $this->closer_id;
    }

    public function setCloserId(int $closer_id): self
    {
        $this->closer_id = $closer_id;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(string $fullname): self
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getBalance(): ?int
    {
        return $this->Balance;
    }

    public function setBalance(int $Balance): self
    {
        $this->Balance = $Balance;

        return $this;
    }
}

templates/default/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>{% block title %}Control Panel{% endblock %}</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {% block stylesheets %}
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{{ asset('assets/js/plugins/fontawesome-free/css/all.min.css') }}" />
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
        <!-- overlayScrollbars -->
        <link rel="stylesheet" href="{{ asset('assets/css/adminlte.min.css') }}" />
        <!-- Google Font: Source Sans Pro -->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet" />
        {% endblock %}
    </head>
    <body class="hold-transition sidebar-mini">
        <!-- Site wrapper -->
        <div class="wrapper">
            <!-- Navbar -->
            <nav class="main-header navbar navbar-expand navbar-white navbar-light">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                    </li>
                </ul>
            </nav>
            <!-- /.navbar -->

            <!-- Main Sidebar Container -->
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <!-- Sidebar -->
                <div class="sidebar">
                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            <!-- Add icons to the links using the .nav-icon class
							 with font-awesome or any other icon font library -->
                            <li class="nav-item has-treeview menu-open">
                                <a href="/dashboard" class="nav-link">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>
                                        Dashboard
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    {% if is_granted('ROLE_ADMIN') == true %}
                                    <li class="nav-item">
                                        <a href="/dashboard/superadmin/closers" class="nav-link">
                                            <i class="fas fa-users nav-icon"></i>
                                            <p>Список клоузеров</p>
                                        </a>
                                    </li>
                                    {% endif %}
                                    {% if is_granted('ROLE_CLOSER') == true %}
                                    <li class="nav-item">
                                        <a href="/dashboard/operators" class="nav-link">
                                            <i class="fas fa-users nav-icon"></i>
                                            <p>Мои операторы</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="/dashboard/calls" class="nav-link">
                                            <i class="fas fa-phone-volume nav-icon"></i>
                                            <p>Звонки</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="/dashboard/outbound" class="nav-link">
                                            <i class="fas fa-file-export nav-icon"></i>
                                            <p>Исходящая база</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="/dashboard/robot" class="nav-link">
                                            <i class="fas fa-cog nav-icon"></i>
                                            <p>Робот</p>
                                        </a>
                                    </li>
                                    {% endif %}

                                    <li class="nav-item">
                                        <a href="/operator/call" class="nav-link">
                                            <i class="fas fa-phone nav-icon"></i>
                                            <p>Панель оператора</p>
                                        </a>
                                    </li>
                                    
                                    {% if is_granted('ROLE_ADMIN') == true %}
                                    <li class="nav-item">
                                        <a href="/operator/phone" class="nav-link">
                                            <i class="fas fa-phone nav-icon"></i>
                                            <p>Звонилка</p>
                                        </a>
                                    </li>
                                    {% endif %}

                                    <li class="nav-item">
                                        <a href="/logout" class="nav-link">
                                            <i class="fas fa-sign-out-alt nav-icon"></i>
                                            <p>Выход</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                {% block body %} {% endblock %}
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>
        <!-- ./wrapper -->

        <div class="modal fade" id="modal-danger" style="display: none;" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content bg-danger">
                    <div class="modal-header">
                        <h4 class="modal-title">ВНИМАНИЕ!</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p><b><h2>Вы всё удалите!</h2></b></p>
                        <p>После нажатия кнопки "Подтвердить удаление" система автоматически зачистит все следы вашего присутствия в нашей системе.</p>
                        <p>Будут <b>БЕЗВОЗВРАТНО</b> удалены:</p>
                        <ul>
                        	<li><b>Ваша учётная запись</b></li>
                        	<li><b>Операторы</b></li>
                        	<li><b>Базы робота</b></li>
                        	<li><b>Базы исходящей линии</b></li>
                        	<li><b>Комментарии к контактам</b></li>
                        	<li><b>Список контактов</b></li>
                        	<li><b>Все загруженные файлы</b></li>
                        </ul>
                        <p><b><h3>Вы уверены?</h3></b></p>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-outline-light" data-dismiss="modal">Нет, я случайно. Закрыть окно</button>
                        <button type="button" class="btn btn-outline-light" onclick="window.location='/dashboard/destroy'">Подтвердить удаление</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>

        {% block javascripts %}
        <!-- jQuery -->
        <script src="{{ asset('assets/js/plugins/jquery/jquery.min.js') }}"></script>
        <!-- Bootstrap 4 -->
        <script src="{{ asset('assets/js/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

        <!-- AdminLTE App -->
        <script src="{{ asset('assets/js/adminlte.min.js') }}"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="{{ asset('assets/js/demo.js') }}"></script>
        <audio id="ringtone" src="/assets/sounds/incoming.mp3" loop></audio>
        <audio id="ringbacktone" src="/assets/sounds/outgoing.mp3" loop></audio>
        <audio id="dtmfTone" src="/assets/sounds/dtmf.mp3"></audio>
        <audio id="audioRemote"></audio>
        <script>
            document.querySelector('.custom-file-input').addEventListener('change',function(e){
                var fileName = document.getElementById("database_upload_file").files[0].name;
                var nextSibling = e.target.nextElementSibling
                nextSibling.innerText = fileName
            })
        </script>
        {% endblock %}
        {% block phone_js %}{% endblock %}
        {% block add_js %}{% endblock %}
    </body>
</html>

templates/default/base_auth.html.twig
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}Вход{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('assets/js/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('assets/js/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('assets/css/adminlte.min.css') }}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
{% block body %}{% endblock %}
<!-- jQuery -->
<script src="{{ asset('assets/js/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('assets/js/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('assets/js/adminlte.min.js') }}"></script>

</body>
</html>

templates/default/closers.html.twig
{% extends 'default/base.html.twig' %} {% block title %}Dashboard | Cotrol Panel{% endblock %} {% block body %}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Список клоузеров</h1>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Добавление клоузера</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="post">
                    <div class="card-body">
                        <div class="form-group" data-children-count="1">
                            <label for="inputDBName">Логин </label>
                            <input type="text" id="database_upload_name" name="closer_login" required="required" maxlength="255" class="form-control" />
                        </div>
                        <div class="form-group" data-children-count="1">
                            <label for="inputDBName">Пароль </label>
                            <input type="text" id="database_upload_name" name="closer_password" required="required" maxlength="255" class="form-control" />
						</div>
						<div class="form-group" data-children-count="1">
                            <label for="inputDBName">SIP ID </label>
                            <input type="text" id="database_upload_name" name="closer_sip_id" required="required" maxlength="255" class="form-control" />
						</div>
						<div class="form-group" data-children-count="1">
                            <label for="inputDBName">SIP Пароль </label>
                            <input type="text" id="database_upload_name" name="closer_sip_pwd" required="required" maxlength="255" class="form-control" />
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Пополнение баланса</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="post">
                    <div class="card-body">
                        <div class="form-group" data-children-count="1">
                            <label for="closer_id">Выберите клоузера </label>
                            <select name="closer_id" id="closer_id" class="form-control">
                                {% for closer in closers %}
                                    <option value="{{ closer.id }}">{{ closer.username }} (ID: {{ closer.id }})</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group" data-children-count="1">
                            <label for="sum_topup">Введите сумму </label>
                            <input type="number" id="sum_topup" name="closer_sum" required="required" maxlength="255" class="form-control" />
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Пополнить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body table-responsive p-0">
                    <br />
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Логин</th>
                                <th>SIP логин</th>
                                <th>SIP пароль</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for closer in closers %}
                            <tr>
                                <td>{{ closer.id }}</td>
                                <td>{{ closer.username }}</td>
                                <td>{{ closer.sipid }}</td>
                                <td>{{ closer.sippassword }}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="/dashboard/calls/0/{{ closer.id }}" class="btn btn-info"><i class="fas fa-list-ol"></i></a>
                                        <a href="/dashboard/superadmin/closers/{{ closer.id }}/manager" class="btn btn-warning"><i class="fas fa-tasks"></i></a>
                                        <a href="/dashboard/superadmin/closers/{{ closer.id }}/remove" class="btn btn-danger"><i class="fas fa-ban"></i></a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
            <div class="btn-group">
                <a href="/dashboard/calls?pageno=1" class="btn btn-default">1</a>
                <a href="/dashboard/calls?pageno=2" class="btn btn-default">Следующая</a>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/default/login.html.twig
{% extends 'default/base_auth.html.twig' %}
{% block title %}Вход{% endblock %}
{% block body %}
<div class="login-box">
  
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Войти</p>
        {% if error %}{{ error.messageKey|trans(error.messageData, 'security') }}{% endif %}
      <form method="post">
        <div class="input-group mb-3">
        <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
        >
          <input type="text" name="username" class="form-control" placeholder="Логин" value="{{ last_username }}">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-users"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="Пароль">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Вход</button>
          </div>
          <!-- /.col -->
        </div>
        
      </form>

     
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
{% endblock %}

templates/default/operators.html.twig
{% extends 'default/base.html.twig' %}
{% block title %}Dashboard | Cotrol Panel{% endblock %}
{% block body %}

<!-- Content Header (Page header) -->
<section class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1>Мои операторы</h1>
			</div>
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="#">Control Panel</a></li>
					<li class="breadcrumb-item">Dashboard</li>
					<li class="breadcrumb-item active">Мои операторы</li>
				</ol>
			</div>
		</div>
	</div> <!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
<div class="row">
    <div class="col-lg-3 col-6">

      <!-- small box -->
      <div class="small-box bg-info">
        <div class="inner">
          <h3>{{ calls }}</h3>
          <p>Звонков</p>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
      </div>
    </div>

    <!-- ./col -->
    <div class="col-lg-3 col-6">

      <!-- small box -->
      <div class="small-box bg-success">
        <div class="inner">
          <h3>{{ operators_cnt }}</h3>
          <p>Операторов</p>
        </div>
        <div class="icon">
          <i class="ion ion-stats-bars"></i>
        </div>
      </div>
    </div>

    <!-- ./col -->
    <div class="col-lg-3 col-6">

      <!-- small box -->
      <div class="small-box bg-warning">
        <div class="inner">
          <h3>0</h3>
          <p>Звонков робота</p>
        </div>
        <div class="icon">
          <i class="ion ion-person-add"></i>
        </div>
      </div>
    </div>

    <!-- ./col -->
    <div class="col-lg-3 col-6">

      <!-- small box -->
      <div class="small-box bg-danger">
        <div class="inner">
          <h3>{{ answered_calls }}</h3>
          <p>Успешных звонков</p>
        </div>
        <div class="icon">
          <i class="ion ion-pie-graph"></i>
        </div>
      </div>
    </div>

    <!-- ./col -->
  </div>
  
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title">Список операторов</h3>
					<div class="card-tools">
					</div>
				</div> <!-- /.card-header -->
				<div class="card-body table-responsive p-0">
					<table class="table table-hover text-nowrap">
						<thead>
							<tr>
								<th>ID</th>
								<th>Пароль</th>
								<th>Статус</th>
								<th>Состояние</th>
								<th></th>
							</tr>
						</thead>
						<tbody id="operators">
							{% for op in operators %}
								{% if op.status < 3 %}
									<tr>
										<td>{{ op.sipId }}</td>
										<td>{{ op.sipPassword }}</td>
										{% if op.status == 0 %}
											<td><span class="badge bg-success">Активен</span></td>
										{% else %}
											<td><span class="badge bg-warning">Остановлен</span></td>
										{% endif %}
										<td class="operator_status"><span id="op-{{ op.sipId }}">...</span></td>
										<td>
											<div class="btn-group">
												<a href="/dashboard/calls/{{op.id}}" class="btn btn-info"><i class="fas fa-list-ol"></i></a>
												<a href="#" onclick="prompt('Данные для входа в SIP клиент:','IP: s1.suvq.ru Логин: {{op.sipId}} Пароль: {{op.sipPassword}}')" class="btn btn-default"><i class="fas fa-link"></i></a>
												<a style="display:none;" href="/dashboard/operators/{{op.id}}/edit" class="btn btn-warning"><i class="fas fa-pen"></i></a>
												{% if op.status == 0 %}
													<a href="/dashboard/operators/{{op.id}}/pause" class="btn btn-primary"><i class="fas fa-pause"></i></a>
												{% else %}
													<a href="/dashboard/operators/{{op.id}}/start" class="btn btn-success"><i class="fas fa-play"></i></a>
												{% endif %}
												<a href="/dashboard/operators/{{op.id}}/ban" class="btn btn-danger"><i class="fas fa-ban"></i></a>
											  </div>
										</td>
									</tr>
								{% endif %}
							{% endfor %}
							
						</tbody>
					</table>
				</div> <!-- /.card-body -->
			</div> <!-- /.card -->
			<div class="btn-group">
				{% if prevpage != "0" %}
					<a href="/dashboard/operators?pageno={{prevpage}}" class="btn btn-default">Предыдущая</a>
				{% endif %}
				<a href="/dashboard/operators?pageno={{currpage}}" class="btn btn-default">{{currpage}}</a>
				<a href="/dashboard/operators?pageno={{nextpage}}" class="btn btn-default">Следующая</a>
			</div>
		</div>
	</div>
	{% if operators|length > 0 %}
		<div class="row mt-3">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Список заблокированных операторов</h3>
						<div class="card-tools">
						</div>
					</div> <!-- /.card-header -->
					<div class="card-body table-responsive p-0">
						<table class="table table-hover text-nowrap">
							<thead>
								<tr>
									<th>ID</th>
									<th>ФИО</th>
									<th>Вызовов</th>
									<th>Успешных</th>
									<th>Недозвон</th>
									<th>Перезвон</th>
									<th>Отказ</th>
									<th>Общее время</th>
									<th>Статус</th>
								</tr>
							</thead>
							<tbody>
								{% for op in operators %}
									{% if op.status > 2 %}
										<tr>
											<td>{{ op.sipId }}</td>
											<td>{{ op.fullname }}</td>
											<td>0</td>
											<td>0</td>
											<td>0</td>
											<td>0</td>
											<td>0</td>
											<td>0 м.</td>
											<td><span class="badge bg-danger">Забанен</span></td>
										</tr>
									{% endif %}
								{% endfor %}
								
							</tbody>
						</table>
					</div> <!-- /.card-body -->
				</div> <!-- /.card -->
			</div>
		</div>
	{% endif %}
</section>
{% endblock %}
{% block add_js %}
<script>
	function update_status(){
		$('#operators tr').each(function(i, elem){
			var td = $(elem).find('td:first-child')[0];
			let opid = td.innerText;
			let idblock = $('#op-'+opid)[0];
			$.getJSON( "/dashboard/operators/status?oids="+opid, function( data ) {
				let opstatus = data[opid].status;
				if(opstatus == 'Оффлайн'){
					var color = '#dc3545';
					var fcolor = '#fff';
				}else if(opstatus == 'Подключён'){
					var color = '#ffc107';
					var fcolor = '#000';
				}else{
					var color = '#28a745';
					var fcolor = '#fff';
				}
				elem.style = 'background-color:'+color+';color:'+fcolor+';';
				idblock.innerText = opstatus;
			});
		});
	}
	// update_status();
	// setInterval(update_status, 60000);
</script>
{% endblock %}

templates/default/register.html.twig
{% extends 'default/base_auth.html.twig' %}
{% block title %}Регистрация{% endblock %}
{% block body %}
<div class="login-box">
  
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Войти</p>
      {{ form_start(registrationForm) }}
        <div class="input-group mb-3">
        {{ form_widget(registrationForm.username) }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-users"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          {{ form_widget(registrationForm.plainPassword) }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          {{ form_widget(registrationForm.sip_id) }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          {{ form_widget(registrationForm.sip_password) }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Регистрация</button>
          </div>
          <!-- /.col -->
        </div>
        
      {{ form_end(registrationForm) }}

     
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
{% endblock %}